project_id = "tfbttrvqfdtmuhmmwksj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-creative]
    verify_jwt = false
  [functions.scrape-product]
    verify_jwt = false
  [functions.optimize-prompt]
    verify_jwt = false
  [functions.generate-ad-copy]
    verify_jwt = false
  [functions.refine-image]
    verify_jwt = false
